name: Generate 3D Contribution Visualization

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Generate 3D contribution graph
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: node scripts/generate-3d-contrib.js

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ secrets.GH_PAT }}

